name: CI Build And Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:1.20
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}